# Colors (Ubuntu)
colors:
  # Default colors
  primary:
    background: '#1F1726'
    foreground: '#DAFAFF'

  # Normal colors
  normal:
    black:   '#000507'
    red:     '#D94085'
    green:   '#2AB250'
    yellow:  '#FFD16F'
    blue:    '#883CDC'
    magenta: '#ECECEC'
    cyan:    '#C1B8B7'
    white:   '#FFF8DE'

  # Bright colors
  bright:
    black:   '#009CC9'
    red:     '#DA6BAC'
    green:   '#F4DCA5'
    yellow:  '#EAC066'
    blue:    '#308CBA'
    magenta: '#AE636B'
    cyan:    '#FF919D'
    white:   '#E4838D'
