#!/bin/bash

DIR="/home/alguien/.config/polybar"
PNT=";dunstify -i $HOME/.config/dunst/iconpng/arch.png"

elementary_bar="rm -rf $DIR/launch.sh && cp $DIR/elemntary/launch.sh $DIR/launch.sh$PNT elementary bar establecida"
blocks_bar="rm -rf $DIR/launch.sh && cp $DIR/blocks/launch.sh $DIR/launch.sh$PNT blocks bar establecida"
forest_bar="rm -rf $DIR/launch.sh && cp $DIR/forest/launch.sh $DIR/launch.sh$PNT Forest bar establecida"
reload_sxhkd="$PNT quizá luego"
reb="$PNT quizá despues"
shut="$PNT talvez Más tarde"

cmds="\
               elementary	${shut}
               blocks		${reb}
               forest		${reload_sxhkd}
               Recargar_Sxhkd	 ${forest_bar}
               Reiniciar PC	${blocks_bar}
               Apagar PC	${elementary_bar}"

choice="$(echo "$cmds" | cut -d'	' -f 1 | rofi -p " Intento de cambio de barra" -dmenu -lines 6 -width 30  )" || exit 1


action=$(echo "$cmds" | grep "^$choice	" | cut -d '	' -f2)

IFS=';' read -ra com <<< "$action"

for i in "${com[@]}"
do
$i
done

