#! /bin/sh

#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-__-_-_-_
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
# 
#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-__-_-_-_

#userChrome.css_____________________inicio_____________________#

~/export_x_info
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh & 
setxkbmap -layout us -variant intl &
#setxkbmap us &
unclutter &
mpd &
~/.config/scripts/services/mpd-ntif.sh &
~/.config/scripts/services/infinite-wa.sh & 
~/.config/scripts/services/greenclip.sh & 
~/.config/scripts/services/touchegg.sh & 
dunst &
touchegg &
greenclip daemon &
xinput --set-prop "11" "libinput Accel Speed" 0.5 &

#_____________________polkit______________________________________

if [ -f /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 ]; then 
  /usr/lib/policykit-1-gnome/polkit-gnome- authentication-agent-1 &
fi

#_____________________config de los monitores_____________________#

if xrandr -q | grep 'HDMI2 connected'; then
xrandr --output HDMI2 --mode 1360x768 --right-of eDP1
bspc monitor -d I IV V VII
bspc monitor HDMI2 -d I II III VI VIII
bspc config pointer_follows_focus true
else
bspc monitor eDP1 -d I II III IV V VI VII VIII
fi

xrandr --output eDP1 --mode 1920x1080 
#bspc monitor -d  一 二 三 四 五 六 七 八 九 零
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 0000 0001 0010 0011 0100 0101 0111 1000 1100
#bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9
#bspc monitor eDP -n 0 -d I II III IV V 
#bspc monitor HDMI1 -n 1 -d VI VII VIII IX X

#______________________

bspc config border_width 	2
bspc config active_border_color #ff0000
bspc config normal_border_color #611a1a 
bspc config window_gap 		3
bspc config split_ratio         0 
bspc config borderless_monocle   true
bspc config gapless_monocle true
#bspc config focus_follows_pointer true
bspc config directional_focus_tightness low
bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config pointer_modifier mod4
bspc config focused_frame_opacity 0.05

#____________________reglas del escritorio____________________#

bspc rule -a Onboard state=floating follow=on
bspc rule -a gnome-calculator state=floating follow=on
bspc rule -a Gedit state=floating follow=on
bspc rule -a File-roller:file-roller state=floating follow=on
bspc rule -a Google-chrome:google-chrome state=fullscreen

picom --experimental-backend &
~/.config/scripts/enviroment/wal.sh &
