#! /bin/sh

#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-__-_-_-_
#
#██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
#██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
#██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#
#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-__-_-_-_

#_____________________inicio_____________________#

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/scripts/wal.sh &
~/.config/polybar/launch.sh &
setxkbmap latam basic &
unclutter &
mpd &
killall mpd-notification ; mpd-notification &
greenclip daemon &
picom --experimental-backend &

#_____________________config de los monitores_____________________#

#bspc monitor -d  一 二 三 四 五 六 七 八 九 零
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 0000 0001 0010 0011 0100 0101 0111 1000 1100
bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc monitor eDP -n 0 -d I II III IV V 
#bspc monitor HDMI1 -n 1 -d VI VII VIII IX X

#______________________

bspc config border_width 	2
bspc config active_border_color #ff0000
bspc config normal_border_color #611a1a 
bspc config window_gap 		3
bspc config split_ratio         0 
bspc config borderless_monocle   true
bspc config gapless_monocle true
#bspc config focus_follows_pointer true
bspc config directional_focus_tightness low
bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config pointer_modifier mod4
bspc config focused_frame_opacity 0.05


#____________________reglas del escritorio____________________#

bspc rule -a Onboard state=floating follow=on
