#!/bin/bash

DIR=/home/alguien/.config
TEN=temas/Pink

cat $DIR/alacritty/$TEN > $DIR/alacritty/alacritty.yml &
cat $DIR/bspwm/$TEN > $DIR/bspwm/bspwmrc & 
cat $DIR/sxhkd/$TEN > $DIR/sxhkd/sxhkdrc &
cat $DIR/dunst/$TEN > $DIR/dunst/dunstrc &
cat $DIR/gtk-3.0/$TEN > $DIR/gtk-3.0/settings.ini &
killall dunst &
cat $DIR/rofi/$TEN > $DIR/rofi/config.rasi &
spicetify config current_theme Material-Ocean &
spicetify apply &
cat $DIR/polybar/material/launch.sh > $DIR/polybar/launch.sh &
bspc wm -r;dunstify -i $HOME/.config/dunst/iconpng/ram.png "Tema Pink correctamente aplicado" &
pkill -USR1 -x sxhkd

